/**
 * Packing API
 * API for creating packing slips
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The UserDTO model module.
* @module model/UserDTO
* @version 0.1
*/
export default class UserDTO {
    /**
    * Constructs a new <code>UserDTO</code>.
    * @alias module:model/UserDTO
    * @class
    * @param username {String} 
    * @param password {String} 
    */

    constructor(username, password) {
        
        
        this['username'] = username;
        this['password'] = password;
        
    }

    /**
    * Constructs a <code>UserDTO</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/UserDTO} obj Optional instance to populate.
    * @return {module:model/UserDTO} The populated <code>UserDTO</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserDTO();
                        
            
            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} username
    */
    username = undefined;
    /**
    * @member {String} password
    */
    password = undefined;


    /**
    * @return {String}
    */
    getUsername() {
        return this.username;
    }

    /**
    * @param {String} username
    */
    setUsername(username) {
        this['username'] = username;
    }
    /**
    * @return {String}
    */
    getPassword() {
        return this.password;
    }

    /**
    * @param {String} password
    */
    setPassword(password) {
        this['password'] = password;
    }


}
